# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-xml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: google-java-format
        name: google-java-format
        entry: google-java-format --replace
        language: system
        files: \.java$
